#version 450
#extension GL_EXT_shader_atomic_float : enable

#include "SegmentTree.glh"

layout(set = 0, binding = 0) buffer SegmentTreeBuffer {
	float[] data;
} segmentTreeBuffer;

layout(set = 0, binding = 1) uniform SegmentTreeGenerationSettings {
	Jimara_SegmentTree_BuildSettings settings;
} segmentTreeGenerationSettings;

Jimara_SegmentTree_ImplementProductKernel(segmentTreeGenerationSettings.settings, segmentTreeBuffer.data, 256)
