image: 
  - Visual Studio 2019

environment:
  VULKAN_SDK: C:/VulkanSDK/1.3.211.0

cache:
  - c:\VulkanSDK\
  - VulkanRT.exe

install:
  - if not exist %VULKAN_SDK% curl -L --silent --show-error --output VulkanSDK.exe https://sdk.lunarg.com/sdk/download/1.3.211.0/windows/VulkanSDK-1.3.211.0-Installer.exe && VulkanSdk install --al --am -c
  - set PATH=%PATH%;%VULKAN_SDK%\Bin
  - if not exist VulkanRT.exe curl -L --silent --show-error --output VulkanRT.exe "https://sdk.lunarg.com/sdk/download/1.3.211.0/windows/VulkanRT-1.3.211.0-Installer.exe"
  - VulkanRT /S
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - python jimara_initialize.py --no_elevate --no_pause
  - NuGet restore Project\Windows\MSVS2019\Jimara.sln

configuration: [Debug, Release]

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - msbuild Project\Windows\MSVS2019\Jimara.sln /p:Configuration=%CONFIGURATION% /p:Platform="x64"

after_build:
  - |
      set BUILD_PATH=__BUILD__\MSVS2019\Jimara-Editor\x64\%CONFIGURATION%\
      set STRIPPED_PATH=__BUILD__\Editor-Artifact
      mkdir %STRIPPED_PATH%
      mkdir %STRIPPED_PATH%\Assets
      copy "%BUILD_PATH%glfw3.dll" "%STRIPPED_PATH%\glfw3.dll"
      copy "%BUILD_PATH%OpenAL32.dll" "%STRIPPED_PATH%\OpenAL32.dll"
      copy "%BUILD_PATH%Jimara.dll" "%STRIPPED_PATH%\Jimara.dll"
      copy "%BUILD_PATH%Jimara.dll" "%STRIPPED_PATH%\Jimara.dll"
      copy "%BUILD_PATH%Jimara-Editor.exe" "%STRIPPED_PATH%\Jimara-Editor.exe"
      cp -r %BUILD_PATH%Game\ %STRIPPED_PATH%\Game
      DEL "%STRIPPED_PATH%\Game\*.pdb" /S /Q
      7z a Jimara-Editor-"%CONFIGURATION%"-x64.zip ./%STRIPPED_PATH%\*

artifacts:
  - path: '*.zip'

test_script:
  - cd __BUILD__\MSVS2019\Jimara-Test\x64\%CONFIGURATION%
  - set JIMARA_TESTS_TO_RUN="ActionQueueTest.*"
  - set JIMARA_TESTS_TO_RUN=%JIMARA_TESTS_TO_RUN%:"ClipboardTest.*"
  - set JIMARA_TESTS_TO_RUN=%JIMARA_TESTS_TO_RUN%:"DynamicLibraryTest.*"
  - set JIMARA_TESTS_TO_RUN=%JIMARA_TESTS_TO_RUN%:"EventTest.*"
  - set JIMARA_TESTS_TO_RUN=%JIMARA_TESTS_TO_RUN%:"FileSystemTest.*"
  - set JIMARA_TESTS_TO_RUN=%JIMARA_TESTS_TO_RUN%:"FunctionTest.*"
  - set JIMARA_TESTS_TO_RUN=%JIMARA_TESTS_TO_RUN%:"InputEnumTest.*"
  - set JIMARA_TESTS_TO_RUN=%JIMARA_TESTS_TO_RUN%:"JobSystemTest.*"
  - set JIMARA_TESTS_TO_RUN=%JIMARA_TESTS_TO_RUN%:"LoggerTest.*"
  - set JIMARA_TESTS_TO_RUN=%JIMARA_TESTS_TO_RUN%:"ObjectTest.*"
  - set JIMARA_TESTS_TO_RUN=%JIMARA_TESTS_TO_RUN%:"PhysicsQueryTest.*"
  - set JIMARA_TESTS_TO_RUN=%JIMARA_TESTS_TO_RUN%:"PropertyTest.*"
  - set JIMARA_TESTS_TO_RUN=%JIMARA_TESTS_TO_RUN%:"ReferenceTest.*"
  - set JIMARA_TESTS_TO_RUN=%JIMARA_TESTS_TO_RUN%:"SerializationMacroTest.*"
  - set JIMARA_TESTS_TO_RUN=%JIMARA_TESTS_TO_RUN%:"SerializeToJsonTest.*"
  - set JIMARA_TESTS_TO_RUN=%JIMARA_TESTS_TO_RUN%:"SPIRV_BinaryTest.BasicReadFromFile_*"
  - set JIMARA_TESTS_TO_RUN=%JIMARA_TESTS_TO_RUN%:"StacktorTest.*"
  - set JIMARA_TESTS_TO_RUN=%JIMARA_TESTS_TO_RUN%:"StopwatchTest.*"
  - Jimara-Test.exe --gtest_filter=%JIMARA_TESTS_TO_RUN%
