image: 
  - Visual Studio 2019

environment:
  VULKAN_SDK: C:/VulkanSDK/1.3.211.0

cache:
  - VulkanSDK.exe

install:
  - curl -L --silent --show-error --output VulkanSDK.exe https://sdk.lunarg.com/sdk/download/1.3.211.0/windows/VulkanSDK-1.3.211.0-Installer.exe
  - VulkanSdk install --al --am -c
  - set PATH=%PATH%;%VULKAN_SDK%
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

build_script:
  - glslc -h
  - python jimara_initialize.py --no_elevate --no_pause
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - NuGet restore Project\Windows\MSVS2019\Jimara.sln
  - msbuild Project\Windows\MSVS2019\Jimara.sln /p:Configuration=Debug /p:Platform="x64"
  - msbuild Project\Windows\MSVS2019\Jimara.sln /p:Configuration=Release /p:Platform="x64"

after_build:
  - |
      7z a Jimara_Debug_x64.zip           __BUILD__\MSVS2019\Jimara\x64\Debug
      7z a Jimara_Release_x64.zip         __BUILD__\MSVS2019\Jimara\x64\Release
      
      7z a Jimara-Editor_Debug_x64.zip    __BUILD__\MSVS2019\Jimara-Editor\x64\Debug
      7z a Jimara-Editor_Release_x64.zip  __BUILD__\MSVS2019\Jimara-Editor\x64\Release

      7z a Jimara-Tests_Debug_X64.zip     __BUILD__\MSVS2019\Jimara-Test\x64\Debug
      7z a Jimara-Tests_Release_X64.zip   __BUILD__\MSVS2019\Jimara-Test\x64\Release

artifacts:
  - path: '*.zip'

test_script:
  - __BUILD__\MSVS2019\Jimara-Test\x64\Debug\Jimara-Test.exe
