image: 
  - Visual Studio 2019

cache:
  - VulkanSDK.exe

install:
  - rm -f VulkanSDK.exe
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

build_script:
  - python jimara_initialize.py --no_elevate --no_pause
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - NuGet restore Project\Windows\MSVS2019\Jimara\Jimara.vcxproj
  - NuGet restore Project\Windows\MSVS2019\Jimara-Editor\Jimara-Editor.vcxproj
  - NuGet restore Project\Windows\MSVS2019\Jimara-Test\Jimara-Test.vcxproj
  - msbuild Project\Windows\MSVS2019\Jimara.sln /p:Configuration=Debug /p:Platform="x64"
  - msbuild Project\Windows\MSVS2019\Jimara.sln /p:Configuration=Release /p:Platform="x64"
  - msbuild Project\Windows\MSVS2019\Jimara.sln /p:Configuration=Debug /p:Platform="x86"
  - msbuild Project\Windows\MSVS2019\Jimara.sln /p:Configuration=Release /p:Platform="x86"

after_build:
  - |
      7z a Jimara_Debug_x64.zip           __BUILD__\MSVS2019\Jimara\x64\Debug
      7z a Jimara_Release_x64.zip         __BUILD__\MSVS2019\Jimara\x64\Release
      7z a Jimara_Debug_x86.zip           __BUILD__\MSVS2019\Jimara\Win32\Debug
      7z a Jimara_Release_x86.zip         __BUILD__\MSVS2019\Jimara\Win32\Release
      
      7z a Jimara-Editor_Debug_x64.zip    __BUILD__\MSVS2019\Jimara-Editor\x64\Debug
      7z a Jimara-Editor_Release_x64.zip  __BUILD__\MSVS2019\Jimara-Editor\x64\Release
      7z a Jimara-Editor_Debug_x86.zip    __BUILD__\MSVS2019\Jimara-Editor\Win32\Debug
      7z a Jimara-Editor_Release_x86.zip  __BUILD__\MSVS2019\Jimara-Editor\Win32\Release

      7z a Jimara-Tests_Debug_X64.zip     __BUILD__\MSVS2019\Jimara-Test\x64\Debug
      7z a Jimara-Tests_Release_X64.zip   __BUILD__\MSVS2019\Jimara-Test\x64\Release
      7z a Jimara-Tests_Debug_X86.zip     __BUILD__\MSVS2019\Jimara-Test\Win32\Debug
      7z a Jimara-Tests_Release_X86.zip   __BUILD__\MSVS2019\Jimara-Test\Win32\Release

artifacts:
  - path: '*.zip'

test_script:
  - __BUILD__\MSVS2019\Jimara-Test\x64\Debug\Jimara-Test.exe
