#version 460
#extension GL_EXT_ray_tracing : enable

layout (set = 0, binding = 0) uniform writeonly image2D frameBuffer;

layout(location = 0) callableDataEXT vec4 color;

void main() {
	const uvec2 pixelIndex = uvec2(gl_LaunchIDEXT.xy);
	const uvec2 targetSize = uvec2(imageSize(frameBuffer));
	if (pixelIndex.x >= targetSize.x ||
		pixelIndex.y >= targetSize.y)
		return;

	color = vec4(
		float(pixelIndex.x) / (targetSize.x - 1), 
		float(pixelIndex.t) / (targetSize.y - 1), 0.0, 1.0);

	const uint callableIndex = 
		((pixelIndex.x / 128) ^ (pixelIndex.y / 128)) & 1;

	executeCallableEXT(callableIndex, 0);

	imageStore(frameBuffer, ivec2(pixelIndex), color);
}
