#version 450
#extension GL_EXT_shader_image_load_formatted: require
#include "BloomKernel_Mix.glh"

layout(set = 0, binding = BLOOM_KERNEL_MIX_TARGET_BINDING) uniform image2D target;

ivec2 TargetSize() { 
	return imageSize(target).xy; 
}

void AddToTarget(in ivec2 coord, in vec4 bloomAmount) {
	const vec4 baseColor = imageLoad(target, coord);
	imageStore(target, coord, baseColor + bloomAmount);
}
